import { Helmet } from "react-helmet-async";
import { Archive, Scale, Sparkles, Users, Globe, GitBranch, CheckCircle2, Infinity as InfinityIcon } from "lucide-react";

const COMMITMENTS = [
  {
    icon: Archive,
    title: "A permanent public record",
    body: "Every CIAA case we document stays in the archive indefinitely. We do not delete records. Officials retire, governments change, and news cycles move on — but the record remains, permanently accessible to any Nepali citizen.",
  },
  {
    icon: Scale,
    title: "Facts, not opinions",
    body: "We present original documents, legal timelines, and verified facts. We simplify complex legal language so citizens can understand what happened — but we never editorialize. Every claim on this platform is traceable to a primary source.",
  },
  {
    icon: CheckCircle2,
    title: "Human review of every AI-generated summary",
    body: "We use AI to process and summarize large volumes of legal documents faster. But every case summary generated by AI is reviewed by a human volunteer for factual accuracy before it is published. Speed does not come at the cost of accuracy.",
  },
  {
    icon: Globe,
    title: "All data in the public domain",
    body: "The data we collect, clean, and structure is released into the public domain. Journalists, researchers, academics, and citizens are free to use it without restriction. Corruption knowledge should not be proprietary.",
  },
  {
    icon: GitBranch,
    title: "Open source technology",
    body: "All of the software we build — from the case archive to the AI research tools — is open source and freely available. Any organization in any country can take our work and adapt it for their own accountability needs.",
  },
  {
    icon: InfinityIcon,
    title: "Free, forever",
    body: "This platform will never charge for access. No subscriptions. No paywalls. No premium tiers. Public accountability infrastructure should be free to everyone who needs it.",
  },
  {
    icon: Users,
    title: "Volunteer-powered, community-owned",
    body: "Jawafdehi is built entirely by Nepali volunteers. We are not funded by government, political parties, or commercial interests. Our independence is structural — we have no institutional master to serve except the public.",
  },
  {
    icon: Sparkles,
    title: "Technology in service of citizens",
    body: "Corruption-related records are scattered across dozens of government portals, court systems, and public databases — inaccessible to most citizens. We are building the technology to crowdsource and consolidate this knowledge into one permanent, publicly searchable archive. The goal is not a product. It is infrastructure.",
  },
];

const Commitment = () => {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Helmet>
        <title>Our Commitment — Jawafdehi</title>
        <meta name="description" content="Jawafdehi's commitments to the Nepali public: permanent records, factual accuracy, open source technology, and free access forever." />
        <link rel="canonical" href="https://jawafdehi.org/commitment" />
        <meta property="og:site_name" content="Jawafdehi Nepal" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://jawafdehi.org/commitment" />
        <meta property="og:title" content="Our Commitment — Jawafdehi" />
        <meta property="og:description" content="Jawafdehi's commitments to the Nepali public: permanent records, factual accuracy, open source technology, and free access forever." />
        <meta property="og:image" content="https://jawafdehi.org/og-favicon.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Our Commitment — Jawafdehi" />
        <meta name="twitter:description" content="Jawafdehi's commitments to the Nepali public: permanent records, factual accuracy, open source technology, and free access forever." />
        <meta name="twitter:image" content="https://jawafdehi.org/og-favicon.png" />
      </Helmet>

      <main id="main-content" className="flex-1">
        {/* Header */}
        <section className="bg-primary py-16 md:py-24">
          <div className="container mx-auto px-4">
            <div className="max-w-2xl">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary-foreground/50 mb-4">
                Our Commitment
              </p>
              <h1 className="text-4xl md:text-5xl font-bold text-white mb-6 leading-tight">
                Nepal's society deserves a permanent memory of accountability
              </h1>
              <p className="text-lg text-primary-foreground/70 leading-relaxed">
                Corruption cases disappear from public consciousness. Officials retire, change portfolios, or simply wait for people to forget. We are building the infrastructure to make sure that never happens again.
              </p>
            </div>
          </div>
        </section>

        {/* Mission */}
        <section className="py-12 md:py-14 border-b border-border">
          <div className="container mx-auto px-4">
            <div className="max-w-3xl">
              <h2 className="text-2xl font-bold text-foreground mb-5">Our Mission</h2>
              <p className="text-lg text-foreground leading-relaxed mb-4">
                Jawafdehi is dedicated to promoting transparency and accountability in Nepal by documenting, verifying, and publishing corruption cases involving public entities. We empower Nepali citizens with verified information to drive systemic change and hold public officials accountable for their actions.
              </p>
              <p className="text-lg text-muted-foreground leading-relaxed">
                Through rigorous investigation, documentation, and public disclosure, we aim to create a more transparent governance system where corruption is exposed, justice is served, and public trust is restored.
              </p>
            </div>
          </div>
        </section>

        {/* Commitments grid */}
        <section className="py-12 md:py-16">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
              {COMMITMENTS.map(({ icon: Icon, title, body }) => (
                <div key={title} className="flex gap-5">
                  <div className="flex-shrink-0 h-11 w-11 rounded-xl bg-primary/10 flex items-center justify-center mt-0.5">
                    <Icon className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-foreground mb-2">{title}</h3>
                    <p className="text-muted-foreground leading-relaxed text-sm">{body}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

    </div>
  );
};

export default Commitment;
