import {
  Archive,
  CheckCircle2,
  GitBranch,
  Globe,
  Infinity as InfinityIcon,
  Scale,
  Sparkles,
  Users,
  type LucideIcon,
} from "lucide-react";

type CommitmentItem = {
  icon: LucideIcon;
  title: string;
  body: string;
};

const COMMITMENTS: CommitmentItem[] = [
  {
    icon: Archive,
    title: "A permanent public record",
    body: "Every CIAA case we document stays in the archive indefinitely. We do not delete records. Officials retire, governments change, and news cycles move on — but the record remains, permanently accessible to any Nepali citizen.",
  },
  {
    icon: Scale,
    title: "Facts, not opinions",
    body: "We present original documents, legal timelines, and verified facts. We simplify complex legal language so citizens can understand what happened — but we never editorialize. Every claim on this platform is traceable to a primary source.",
  },
  {
    icon: CheckCircle2,
    title: "Human review of every AI-generated summary",
    body: "We use AI to process and summarize large volumes of legal documents faster. But every case summary generated by AI is reviewed by a human volunteer for factual accuracy before it is published. Speed does not come at the cost of accuracy.",
  },
  {
    icon: Globe,
    title: "All data in the public domain",
    body: "The data we collect, clean, and structure is released into the public domain. Journalists, researchers, academics, and citizens are free to use it without restriction. Corruption knowledge should not be proprietary.",
  },
  {
    icon: GitBranch,
    title: "Open source technology",
    body: "All of the software we build — from the case archive to the AI research tools — is open source and freely available. Any organization in any country can take our work and adapt it for their own accountability needs.",
  },
  {
    icon: InfinityIcon,
    title: "Free, forever",
    body: "This platform will never charge for access. No subscriptions. No paywalls. No premium tiers. Public accountability infrastructure should be free to everyone who needs it.",
  },
  {
    icon: Users,
    title: "Volunteer-powered, community-owned",
    body: "Jawafdehi is built entirely by Nepali volunteers. We are not funded by government, political parties, or commercial interests. Our independence is structural — we have no institutional master to serve except the public.",
  },
  {
    icon: Sparkles,
    title: "Technology in service of citizens",
    body: "Corruption-related records are scattered across dozens of government portals, court systems, and public databases — inaccessible to most citizens. We are building the technology to crowdsource and consolidate this knowledge into one permanent, publicly searchable archive. The goal is not a product. It is infrastructure.",
  },
];

export function CommitmentList() {
  return (
    <section id="commitments" className="py-12 md:py-16">
      <div className="container mx-auto px-4">
        <h2 className="mb-10 text-center text-3xl font-extrabold tracking-normal text-primary md:text-4xl">
          Our Commitment
        </h2>

        <div className="grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-6">
          {COMMITMENTS.map(({ icon: Icon, title, body }, index) => (
            <div
              key={title}
              className={[
                "flex flex-col items-center text-center lg:col-span-2",
                index === 6 ? "lg:col-start-2" : "",
                index === 7 ? "lg:col-start-4" : "",
              ].join(" ")}
            >
              <div>
                <div className="mb-2 flex items-center justify-center gap-2">
                  <Icon className="h-5 w-5 flex-shrink-0 text-accent" aria-hidden="true" />
                  <h3 className="text-lg font-semibold text-foreground">{title}</h3>
                </div>
                <p className="mx-auto max-w-sm text-sm leading-relaxed text-muted-foreground">
                  {body}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
